name: houzi_package
description: A new Flutter package.
version: 0.0.1
publish_to: none


environment:
  sdk: '>=3.2.6 <4.0.0'

#  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animate_icons: 2.0.0
  autocomplete_textfield: 2.0.1
  #build_runner: 2.4.6
  cupertino_icons: 1.0.6
  dio: 5.3.3
  dio_cache_interceptor: 3.4.4
  #  dio_http_cache: 0.3.0
  expandable: 5.0.1
  fancy_shimmer_image: 2.0.3
  #  firebase_messaging: 13.0.2
  flutter_dialogs: 3.0.0
  flutter_staggered_grid_view: 0.4.0

  flutter_widget_from_html: 0.15.3
  location: 5.0.3
  geolocator: 10.1.0
  flutter_facebook_auth: 6.0.2
  html_unescape: 2.0.0
  hive_flutter: 1.1.0
  hive: 2.2.3
  hive_generator: 2.0.1
  image_picker: 1.0.4
  #loading_gifs: 0.3.0
  loading_indicator: 3.1.1
  material_segmented_control: 5.0.0
  path_provider: 2.1.1
  pie_chart: 5.4.0
  provider: 6.1.1
  pull_to_refresh: 2.0.0
  shimmer: 3.0.0
  sliding_up_panel: 2.0.0+1
  smooth_page_indicator: 1.1.0
  toggle_switch: 2.1.0
  url_launcher: 6.2.1
  #shared_preferences: 2.2.2

  sign_in_with_apple: 7.0.1
  crypto: 3.0.3
  app_tracking_transparency: 2.0.4

  share_plus: 7.2.1
  google_maps_cluster_manager: 3.0.0+1

  intl_phone_field: 3.2.0

  flutter_cache_manager: 3.3.1

  #****===== IMPORTANT =====****
  # use 2.2.11 if flutter version < 3.7.0
  # use 2.2.23 if 3.7.0 < flutter version < 3.10.2
  pinput: 3.0.1

  #****===== Updates =====****
  # for flutter 3.10.2
  flutter_rating_bar: 4.0.1
  package_info_plus: 4.2.0
  fluster: 1.2.0
  path: 1.9.1

  google_mobile_ads: 5.0.0
  webview_flutter: 4.7.0
  background_downloader: 8.4.3

  timeago: 3.7.1

  flutter_local_notifications: 17.2.2
  in_app_purchase: 3.2.0
  reorderable_grid_view: 2.2.1
  carousel_slider: 5.0.0

  # google
  google_maps_flutter: 2.9.0
  google_sign_in: 6.2.1

  # firbase
  firebase_core: 3.13.0
  firebase_auth: 5.5.3
  firebase_analytics: 11.4.5

  onesignal_flutter: 5.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true