import 'package:dio/dio.dart';
import 'package:houzi_package/models/api/api_request.dart';
import 'package:houzi_package/models/api/api_response.dart';
import 'package:houzi_package/models/article.dart';
import 'package:houzi_package/models/blog_models/blog_articles_data.dart';
import 'package:houzi_package/models/blog_models/blog_comments_data.dart';
import 'package:houzi_package/models/blog_models/blog_details_page_layout.dart';
import 'package:houzi_package/models/blog_models/blog_tags_data.dart';
import 'package:houzi_package/models/blog_models/blogs_categories_data.dart';
import 'package:houzi_package/models/custom_fields/custom_fields.dart';
import 'package:houzi_package/models/drawer/drawer.dart';
import 'package:houzi_package/models/filter_related/filter_page_config.dart';
import 'package:houzi_package/models/form_related/houzi_form_page.dart';
import 'package:houzi_package/models/home_related/home_config.dart';
import 'package:houzi_package/models/listing_related/is_favorite.dart';
import 'package:houzi_package/models/messages/threads.dart';
import 'package:houzi_package/models/messages/messages.dart';
import 'package:houzi_package/models/navbar/navbar_item.dart';
import 'package:houzi_package/models/listing_related/add_update_listing.dart';
import 'package:houzi_package/models/notifications/check_notifications.dart';
import 'package:houzi_package/models/notifications/notifications.dart';
import 'package:houzi_package/models/home_related/partner.dart';
import 'package:houzi_package/models/property_details/property_detail_page_config.dart';
import 'package:houzi_package/models/term.dart';
import 'package:houzi_package/models/realtor_model.dart';
import 'package:houzi_package/models/saved_search.dart';
import 'package:houzi_package/models/home_related/terms_with_icon.dart';
import 'package:houzi_package/models/search/sort_first_by_item.dart';
import 'package:houzi_package/models/user/user.dart';
import 'package:houzi_package/models/user/user_login_info.dart';
import 'package:houzi_package/models/user/user_membership_package.dart';
import 'package:houzi_package/models/user/user_payment_status.dart';

abstract class ApiParser {

  dynamic parseApi(ApiRequest request, Response response);

  Article parseArticle(Map<String, dynamic> json);
  Term parseMetaDataMap(Map<String, dynamic> json);
  Agent parseAgentInfo(Map<String, dynamic> json);
  Agency parseAgencyInfo(Map<String, dynamic> json);
  SavedSearch parseSavedSearch(Map<String, dynamic> json);
  User parseUserInfo(Map<String, dynamic> json);
  ApiResponse<String> parseNonceResponse(Response response);
  Partner parsePartnerJson(Map<String, dynamic> json);
  ApiResponse<String> parsePaymentResponse(Response response);
  ApiResponse<String> parseNormalApiResponse(Response response);
  ApiResponse<String> parseMakeListingFeaturedResponse(Response response);
  ApiResponse<String> parse500ApiResponse(Response response);
  UserMembershipPackage parseUserMembershipPackageResponse(Map<String, dynamic> json);
  BlogArticlesData parseBlogArticlesJson(Map<String, dynamic> json);
  BlogCategoriesData parseBlogCategoriesJson(Map<String, dynamic> json);
  BlogTagsData parseBlogTagsJson(Map<String, dynamic> json);
  BlogCommentsData parseBlogCommentsJson(Map<String, dynamic> json);
  AllNotifications parseAllNotificationsResponse(Map<String, dynamic> json);
  CheckNotifications parseCheckNotificationsResponse(Map<String, dynamic> json);
  Threads parseAllThreadsResponse(Map<String, dynamic> json);
  Messages parseAllMessagesResponse(Map<String, dynamic> json);
  Custom parseCustomFields(Map<String, dynamic> json);
  MembershipPlanDetails parseMembershipPlanDetailsJson(Map<String, dynamic> json);
  BlogDetailsPageLayout parseBlogDetailsPageLayoutJson(Map json);
  HouziFormItem parseFormItemJson(Map<String, dynamic> json);
  HouziFormPage parseFormPageJson(Map<String, dynamic> json);
  DrawerLayoutConfig parseDrawerLayoutConfigJson(Map<dynamic, dynamic> json);
  DrawerLayout parseDrawerLayoutItemJson(Map<String, dynamic> json);
  FilterPageElement parseFilterPageElementJson(Map<String, dynamic> json);
  HomeConfig parseHomeConfigJson(Map<dynamic, dynamic> json);
  TermsWithIcon parseTermsWithIconJson(Map<String, dynamic> json);
  HomeLayout parseHomeLayoutJson(Map<String, dynamic> json);
  NavBar parseNavBarJson(Map<dynamic, dynamic> json);
  NavbarItem parseNavbarItemJson(Map<String, dynamic> json);
  PropertyDetailPageLayout parsePropertyDetailPageLayoutJson(Map<dynamic, dynamic> json);
  PropertyDetailPageLayoutElement parsePropertyDetailPageLayoutElementJson(Map<String, dynamic> json);
  SortFirstBy parseSortFirstByJson(Map<dynamic, dynamic> json);
  SortFirstByItem parseSortFirstByItemJson(Map<String, dynamic> json);
  Agent parseAgentFromJson(Map<String, dynamic> json);
  Agency parseAgencyJson(Map<String, dynamic> json);
  Term parseTermJson(Map<String, dynamic> json);
  AddOrUpdateListing parseAddOrUpdateListingJson(Map<String, dynamic> json);
  UserLoginInfo parseUserLoginInfoJson(Map<String, dynamic> json);
  IsFavourite parseIsFavouriteJson(Map<String, dynamic> json);
  UserPaymentStatus parseUserPaymentStatusJson(Map<String, dynamic> json);


  Map<String, dynamic> convertCustomFieldsToJson(Custom custom);
  Map<String, dynamic> convertBlogDetailsPageLayoutToJson(BlogDetailsPageLayout layout);
  Map<String, dynamic> convertFormItemToJson(HouziFormItem formItem);
  Map<String, dynamic> convertFormPageToJson(HouziFormPage formPage);
  Map<String, dynamic> convertDrawerLayoutConfigToJson(DrawerLayoutConfig config);
  Map<String, dynamic> convertDrawerLayoutItemToJson(DrawerLayout layoutItem);
  Map<String, dynamic> convertFilterPageElementToMap(FilterPageElement filterPageElement);
  Map<String, dynamic> convertHomeConfigToJson(HomeConfig item);
  Map<String, dynamic> convertTermsWithIconToJson(TermsWithIcon item);
  Map<String, dynamic> convertHomeLayoutToJson(HomeLayout item);
  Map<String, dynamic> convertNavBarToJson(NavBar item);
  Map<String, dynamic> convertNavbarItemToJson(NavbarItem navbarItem);
  Map<String, dynamic> convertPropertyDetailPageLayoutToJson(PropertyDetailPageLayout item);
  Map<String, dynamic> convertPropertyDetailPageLayoutElementToJson(PropertyDetailPageLayoutElement item);
  Map<String, dynamic> convertSortFirstByToJson(SortFirstBy item);
  Map<String, dynamic> convertSortFirstByItemToJson(SortFirstByItem item);
  Map<String, dynamic> convertAgentToMap(Agent item);
  Map<String, dynamic> convertAgencyToMap(Agency item);
  Map<String, dynamic> convertTermToMap(Term item);
  Map<String, dynamic> convertAddOrUpdateListingToJson(AddOrUpdateListing item);
  Map<String, dynamic> convertUserLoginInfoToJson(UserLoginInfo item);
  Map<String, dynamic> convertIsFavouriteToJson(IsFavourite item);
  Map<String, dynamic> convertUserPaymentStatusToJson(UserPaymentStatus item);
}