import 'package:houzi_package/api_management/interfaces/api_parser_interface.dart';
import 'package:houzi_package/models/api/api_request.dart';

abstract class WebsiteApiServices {

  ApiRequest featuredPropertiesApi({int? page, int? perPage});
  ApiRequest latestPropertiesApi({int? page, int? perPage});
  ApiRequest filteredPropertiesApi({Map<String, dynamic>? params});
  ApiRequest similarPropertiesApi(int propertyId);
  ApiRequest multiplePropertiesApi(String propertiesId);
  ApiRequest singlePropertyApi(int id, {bool forEditing});
  ApiRequest singleArticleViaPermaLinkApi(String permaLink);
  ApiRequest touchBaseApi();
  ApiRequest provideSingleAgencyApi(int id);
  ApiRequest provideSingleAgentApi(int id);
  ApiRequest provideAgentsOfAgencyApi(int agencyId);
  ApiRequest provideAllAgentsApi(int page, int perPage, bool? visibilityOnly);
  ApiRequest provideAllAgenciesApi(int page, int perPage, bool? visibilityOnly);
  ApiRequest provideListingsByCityApi(int cityId, int page, int perPage);
  ApiRequest provideContactRealtorApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideContactPropertyRealtorApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideContactDeveloperApi(Map<String, dynamic> params);
  ApiRequest provideScheduleATourApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideAddNewListingApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideUpdateListingApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideUploadListingImagesApi({required String userToken, required String userId, required String nonce});
  ApiRequest provideLoginApi(Map<String,dynamic> params, String nonce);
  ApiRequest provideSignUpApi(Map<String,dynamic> params, String nonce);
  ApiRequest provideAdminUserSignUpApi(Map<String, dynamic> params, String userToken, String nonce);
  ApiRequest provideForgotPasswordApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideAllPropertiesApi(String status, int page, int perPage, int? userId);
  ApiRequest provideMyListingsApi(String status, int page, int perPage);
  ApiRequest provideStatusOfListingApi(Map<String, dynamic> params, int id);
  ApiRequest provideDeleteListingApi(int id);
  ApiRequest provideTermDataApi(dynamic termData, {String? parentSlug});
  ApiRequest provideAddOrRemoveFavoritesApi(Map<String, dynamic> params);
  ApiRequest provideSearchAgenciesApi(int page, int perPage, String search);
  ApiRequest provideFavoriteListingsApi(int page, int perPage, String userId);
  ApiRequest provideDeleteImageApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideSaveSearchApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideSavedSearchesListingApi(int page, int perPage, {String? leadId, bool fetchLeadSavedSearches = false});
  ApiRequest provideDeleteSavedSearchApi(Map<String, dynamic> params);
  ApiRequest provideAddReviewApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideReportContentApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideListingReviewsApi(int id, String page, String perPage);
  ApiRequest provideRealtorReviewsApi(int id, String page, String perPage, String type);
  ApiRequest provideUserInfoApi();
  ApiRequest provideUpdateUserProfileApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideFixProfileImageApi();
  Future<ApiRequest> provideUpdateUserProfileImageApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideSearchAgentsApi(int page, int perPage, String search, String agentCity, String agentCategory);
  ApiRequest provideIsFavoriteApi(String listingId);
  ApiRequest provideSocialSingOnApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideDeleteUserAccountApi();
  ApiRequest provideUpdateUserPasswordApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideRequestPropertyApi(Map<String, dynamic> params);
  ApiRequest provideAddAgentApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideEditAgentApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideAllAgentOfAnAgencyApi(int agencyId);
  ApiRequest provideDeleteAnAgentApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideAllUsersApi(int page, int perPage, String search);
  ApiRequest provideUserPaymentStatusApi();
  ApiRequest providePrintPropertyPDFApi(Map<String, dynamic> params);
  ApiRequest provideAllPartnersApi();
  ApiRequest provideDirectionsApi(String platform, String latitude, String longitude);
  ApiRequest provideMembershipPackagesApi(String page, String perPage);
  ApiRequest provideUserMembershipPackageApi();
  ApiRequest provideProceedWithPaymentsApi(Map<String, dynamic> params);
  ApiRequest provideMakePropertyFeaturedApi(Map<String, dynamic> params);
  ApiRequest provideRemoveFromFeaturedApi(Map<String, dynamic> params);
  ApiRequest provideApproveOrDisapproveListingApi(Map<String, dynamic> params);
  ApiRequest provideToggleFeaturedApi(int propertyId, bool setFeatured);
  ApiRequest provideSetSoldStatusApi(int propertyId);
  ApiRequest provideSetExpiredStatusApi(int propertyId);
  ApiRequest provideSetPendingStatusApi(Map<String, dynamic> params);
  ApiRequest provideAllBlogsApi(String page, String perPage);
  ApiRequest provideAllBlogCategoriesApi(String orderBy, String order);
  ApiRequest provideAllBlogTagsApi(String orderBy, String order);
  ApiRequest provideBlogCommentsApi(String page, String perPage, String postId);
  ApiRequest provideAddBlogCommentApi(Map<String, dynamic> params, String nonce);
  ApiRequest provideAllNotificationsApi(String page, String perPage);
  ApiRequest provideCheckNotificationsApi(String page, String perPage);
  ApiRequest provideDeleteNotificationApi(String notificationId, String userEmail);
  ApiRequest provideAllThreadsApi(int page, int perPage, int? propertyId);
  ApiRequest provideAllMessagesApi(Map<String, dynamic> params);
  ApiRequest provideDeleteThreadApi(String threadId, String senderId, String receiverId);
  ApiRequest provideStartThreadApi(int propertyId, String message, String nonce);
  ApiRequest provideSendMessagesApi(String threadId, String message, String nonce);

  ApiRequest provideCreateNonceApi(String nonceName);
  String provideAddAgentNonceKey();
  String provideEditAgentNonceKey();
  String provideDeleteAgentNonceKey();
  String provideScheduleATourNonceKey();
  String provideContactPropertyRealtorNonceKey();
  String provideContactRealtorNonceKey();
  String provideAddPropertyNonceKey();
  String provideUpdatePropertyNonceKey();
  String provideAddImageNonceKey();
  String provideDeleteImageNonceKey();
  String provideAddReviewNonceKey();
  String provideSaveSearchNonceKey();
  String provideSignUpNonceKey();
  String provideResetPasswordNonceKey();
  String provideUpdatePasswordNonceKey();
  String provideUpdateProfileNonceKey();
  String provideUpdateProfileImageNonceKey();
  String provideSignInNonceKey();
  String provideReportContentNonceKey();
  String provideAddCommentNonceKey();
  String provideSendMessageNonceKey();
  String provideStartThreadNonceKey();

  ApiParser getParser();
}